name: Publish to Dev.to

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish articles on dev.to
      uses: sinedied/publish-devto@v2
      id: publish_devto
      with:
        devto_key: ${{ secrets.DEVTO_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: '*.md'
        branch: main
        conventional_commits: true
        dry_run: false
